-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_webhook`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_webhook
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_webhook` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Webhook ID',
  `name` varchar(255) COMMENT 'The human readable name of the handler',
  `description` text COMMENT 'Useful information about this hook',
  `handler` varchar(255) COMMENT 'The class name of the handler application',
  `query_string` varchar(255) COMMENT 'The query parameter of the webhook',
  `processor` varchar(255) COMMENT 'The class name of the processor application',
  `options` text COMMENT 'Serialized data for PHP usage',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_query`(query_string)
)
ENGINE=InnoDB;
