name: CI
on:
  pull_request:
    branches:
      - main
env:
  WEBROOT: "/srv/www"
  CIVI_DIR: "civi-zero"
  EXTENSION_NAME: "webhook-admin"
jobs:
  code-style:
    name: Code style check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --rules=@PSR2 --dry-run -v .
  tests:
    name: Unit tests
    runs-on: ubuntu-20.04
    needs: code-style
    steps:
      - name: Purge MySQL databases
        run: |
          sudo systemctl stop mysql
          sudo rm -rf /var/lib/mysql

      - name: Get civi-zero
        uses: actions/checkout@v3
        with:
          repository: reflexive-communications/civicrm-zero
          path: "${{ env.CIVI_DIR }}"

      - name: Move civi-zero to web root
        run: |
          sudo mkdir -p "${WEBROOT}"
          sudo mv "${CIVI_DIR}" "${WEBROOT}/"
          sudo chown -R "${USER}" "${WEBROOT}/${CIVI_DIR}"

      - name: Setup environment
        run: "${WEBROOT}/${CIVI_DIR}/bin/prepare.sh"

      - name: Install CiviCRM
        run: "${WEBROOT}/${CIVI_DIR}/bin/install.sh ${WEBROOT}/${CIVI_DIR}"

      - name: Get required extension (rc-base)
        uses: actions/checkout@v3
        with:
          repository: reflexive-communications/rc-base
          path: rc-base

      - name: Self checkout
        uses: actions/checkout@v3
        with:
          path: ${{ env.EXTENSION_NAME }}

      - name: Install extensions
        run: |
          ${WEBROOT}/${CIVI_DIR}/bin/extension.sh ${WEBROOT}/${CIVI_DIR} rc-base
          ${WEBROOT}/${CIVI_DIR}/bin/extension.sh ${WEBROOT}/${CIVI_DIR} ${EXTENSION_NAME}

      - name: Run unit tests
        run: "${WEBROOT}/${CIVI_DIR}/bin/tests.sh ${WEBROOT}/${CIVI_DIR} ${EXTENSION_NAME}"
