name: CI
on:
  pull_request:
    branches:
      - main
env:
  INSTALL_DIR: /srv/www/civi-zero
  EXTENSION_NAME: webhook-admin
jobs:
  format:
    name: Check format
    runs-on: ubuntu-20.04
    steps:
      - name: Self checkout
        uses: actions/checkout@v3

      - name: Check code-style (PHP)
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --rules=@PSR2 --dry-run -v .

      - name: Check code-style (other)
        uses: creyD/prettier_action@v4.2
        with:
          dry: true
          prettier_options: --check **/*.{js,css,md,yml,json,html}
  tests:
    name: Unit tests
    runs-on: ubuntu-20.04
    needs: format
    steps:
      - name: Get civi-zero
        uses: actions/checkout@v3
        with:
          repository: reflexive-communications/civicrm-zero

      - name: Setup environment
        run: ./bin/prepare.sh

      - name: Install CiviCRM
        run: ./bin/install.sh ${INSTALL_DIR}

      - name: Get required extension (rc-base)
        uses: actions/checkout@v3
        with:
          repository: reflexive-communications/rc-base
          path: rc-base

      - name: Self checkout
        uses: actions/checkout@v3
        with:
          path: ${{ env.EXTENSION_NAME }}

      - name: Install extensions
        run: |
          ./bin/extension.sh ${INSTALL_DIR} rc-base
          ./bin/extension.sh ${INSTALL_DIR} ${EXTENSION_NAME}

      - name: Run unit tests
        run: ./bin/tests.sh ${INSTALL_DIR} ${EXTENSION_NAME}
